/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ColorPicker;

import java.awt.BorderLayout;

/**
 *
 * @author Alex
 */
public class ComboPanel extends javax.swing.JPanel {

    /**
     * Creates new form ComboPanel
     */
    public ComboPanel() {
        initComponents();
        setLayout(new BorderLayout());
        add(colorInputPanel1,BorderLayout.NORTH);
        add(colorSamplePanel1,BorderLayout.SOUTH);
        repaint();
    }
    
    public void giveCL(ColorListener cl) {
        cl.listen(colorInputPanel1);
        colorInputPanel1.giveCL(cl);
        cl.listen(colorSamplePanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorInputPanel1 = new ColorPicker.ColorInputPanel();
        colorSamplePanel1 = new ColorPicker.ColorSamplePanel();

        javax.swing.GroupLayout colorSamplePanel1Layout = new javax.swing.GroupLayout(colorSamplePanel1);
        colorSamplePanel1.setLayout(colorSamplePanel1Layout);
        colorSamplePanel1Layout.setHorizontalGroup(
            colorSamplePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorSamplePanel1Layout.setVerticalGroup(
            colorSamplePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorSamplePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(colorInputPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorSamplePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ColorPicker.ColorInputPanel colorInputPanel1;
    private ColorPicker.ColorSamplePanel colorSamplePanel1;
    // End of variables declaration//GEN-END:variables
}
